waze:
  trip:
  - name: GIANGVO_LANGHA
    origin:
      lat: 21.014803
      lon: 105.813877
    destination:
      lat: 21.031989
      lon: 105.829945

  - name: BACHKHOA_CHOBENTHANH
    origin:
      lat: 10.772834
      lon: 106.657565
    destination:
      lat: 10.771938
      lon: 106.698216